# -*- coding: utf-8 -*-
"""food_detect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rVPiJAwwC64o6_CGLhzFDmRo1-nAy-2H
"""

!pip show tensorflow

import tensorflow as tf
print(tf.test.gpu_device_name())

#!pip install tensorflow tensorflow_datasets

import tensorflow as tf
import tensorflow_datasets as tfds

# Load the dataset of food images
data = tfds.load("food101", split="train[:80%]", as_supervised=True)
data = data.map(lambda x, y: (x, tf.one_hot(y, depth=101)))
data = data.shuffle(1024).batch(32).prefetch(tf.data.AUTOTUNE)

# Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(224, 224, 3)),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(64, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),
    tf.keras.layers.MaxPooling2D((2, 2)),
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(101, activation='softmax')
])

# Compile and train the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(data, epochs=10)